server:
  port: 8081
  DOCUMENT_FOLDER: ${DOCUMENT_FOLDER:/app/documents}
  #notification: ${HOST:http://localhost:8087}
  notification: ${HOST:http://app-dev.modelsis.net:8087}
  #email_cdmp: notifications-wootoo-@modelsis.sn
  email_cdmp: notifications-wootoo@modelsis.sn
spring:
  sql:
    init:
      mode: always
      platform: postgres
  application:
    name: Cession creance
  datasource:
    password: passer
    url: jdbc:postgresql://${DB_HOST:10.42.1.205}:5432/cdmp
    username: cdmp
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false

  servlet:
    multipart:
      max-file-size: 2000000MB
      max-request-size: 2000000MB

