server:
  port: 8081
  document_folder: ${DOCUMENT_FOLDER:D:/Projets/Finance_islamique/documentLibrary}
spring:
  application:
    name: Cession creance
  datasource:
    initialization-mode: always
    password: passer123
    platform: postgres
    url: jdbc:postgresql://10.42.1.204:5432/cdmp
    username: cdmp
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
