server:
  port: 8081
  document_folder: ${C:/Users/macbookpro/Desktop/Wootoo/DocumentLibrary}
  notification: ${HOST:http://localhost:8087}
  email_cdmp: financeislamique@modelsis.sn
spring:
  sql:
    init:
      mode: always
      platform: postgres
  application:
    name: Cession creance
  datasource:
    password: passer
    url: jdbc:postgresql://localhost:5432/cdmp
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

      ddl-auto=update:properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false

  servlet:
    multipart:
      max-file-size: 2000000MB
      max-request-size: 2000000MB


