server:
  port: 8081
  qrcode_folder: ${qrcode_folder:./src/main/resources/static/img}
  document_folder: ${document_folder:/app/documents/cdmp}
  #document_folder: ${DOCUMENT_FOLDER:D:/Projets/CDMP/DocumentLibrary}
  #document_folder: ${DOCUMENT_FOLDER:/Users/macbookpro/Desktop/Wootoo/DocumentLibrary}

  #notification: ${HOST:http://localhost:8087}
  notification: ${HOST:http://10.42.1.131:8087}
  #notification: ${HOST:http://10.0.0.222:8087}
  ##email_cdmp: notifications-wootoo-@modelsis.sn
  link_front: ${LINK_FRONT:http://10.42.1.134:8081}
  email_cdmp: notifications-wootoo@modelsis.sn
spring:
  flyway:
    enabled: true
    out-of-order: false
  sql:
    init:
      mode: always
      platform: postgres
  application:
    name: Cession creance
  datasource:
    password: passer123
    #url: jdbc:postgresql://${HOST_DB:10.0.0.15:5432}/cdmp
    url: jdbc:postgresql://${HOST_DB:10.42.1.205:5432}/cdmp
    #url: jdbc:postgresql://localhost:5432/cdmp
    username: cdmp
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false

  servlet:
    multipart:
      max-file-size: 2000000MB
      max-request-size: 2000000MB
