server:
  port: 8081
  document_folder: ${DOCUMENT_FOLDER:D:/Projets/CDMP/DocumentLibrary}
  notification: ${HOST:http://localhost:8087}
  email_cdmp: notifications-wootoo-@modelsis.sn
spring:
  sql:
    init:
      mode: always
      platform: postgres
  application:
    name: Cession creance
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/cdmp
    username: cdmp
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false

  servlet:
    multipart:
      max-file-size: 2000000MB
      max-request-size: 2000000MB

