server:
  port: 8082
  #document_folder: ${document_folder:/app/documents/cdmp}
  document_folder: ${DOCUMENT_FOLDER:D:/Projets/CDMP/DocumentLibrary}
  #notification: ${HOST:http://localhost:8087}
  #notification: ${HOST:http://app-dev.modelsis.net:8087}
  notification: ${HOST:http://10.0.0.222:8087}
  #email_cdmp: notifications-wootoo-@modelsis.sn
  email_cdmp: notifications-wootoo@modelsis.sn
spring:
  sql:
    init:
      mode: always
      platform: postgres
  application:
    name: Cession creance
  datasource:
    password: password
   # url: jdbc:postgresql://10.42.1.205:5432/cdmp
    #password: passer
   # url: jdbc:postgresql://${HOST_DB:10.0.0.15:5432}/cdmp
    #url: jdbc:postgresql://${HOST_DB:10.42.1.205:5432}/cdmp
    url: jdbc:postgresql://localhost:5432/cdmp
    username: cdmp
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false

  servlet:
    multipart:
      max-file-size: 2000000MB
      max-request-size: 2000000MB

